# Generated by Django 2.1.5 on 2019-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_time',
            field=models.PositiveIntegerField(verbose_name='Call duration in seconds'),
        ),
        migrations.AlterField(
            model_name='call',
            name='call_type',
            field=models.CharField(choices=[('International', 'International'), ('National', 'National'), ('Domestic', 'Domestic')], default='None', max_length=50),
        ),
    ]
