# Generated by Django 2.1.5 on 2019-01-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20190130_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('International', 'International'), ('National', 'National'), ('Domestic', 'Domestic')], max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='call',
            old_name='call_time',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='call',
            name='call_type',
        ),
        migrations.RemoveField(
            model_name='call',
            name='id',
        ),
        migrations.AddField(
            model_name='call',
            name='type',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='calls.Type'),
        ),
    ]
