# Generated by Django 4.2.3 on 2023-07-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0002_alter_category_options_alter_category_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="line",
            field=models.CharField(
                choices=[("I", "International"), ("N", "National"), ("D", "Domestic")],
                max_length=15,
                unique=True,
            ),
        ),
    ]
