# Generated by Django 2.1.5 on 2019-01-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_auto_20190130_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='call',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calls.Type'),
        ),
    ]
