# Generated by Django 4.2.3 on 2023-07-27 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0003_alter_category_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="call",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="line",
            field=models.CharField(
                choices=[("I", "International"), ("N", "National"), ("D", "Domestic")],
                max_length=2,
                unique=True,
            ),
        ),
    ]
