# Generated by Django 4.2.3 on 2023-07-31 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0004_call_created_on_call_updated_on_alter_category_line"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="call",
            options={
                "ordering": ("-created_on",),
                "verbose_name": "call",
                "verbose_name_plural": "calls",
            },
        ),
    ]
