# Generated by Django 2.1.5 on 2019-02-03 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_auto_20190130_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='call',
            name='duration',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Call duration in seconds'),
        ),
    ]
